path: /
portfolio:
  - Clojure
  - Ruby
  - Python
  - Java
  - Perl
summary:
  - Founder of CodeFu, athenahealth group dedicated to improving development skills and studying interesting topics in Computer Science.
  - Organizer of several <a href="http://coderetreat.org/">coderetreats</a>, events pair programming Conway's Game of Life.
  - Creator of several personal sites using Ruby on Rails.
  - Contributions to several open source projects, including celery_once, CPAN modules and test.chuck.
experience:
  tripadvisor:
    tripadvisor:
      - Eliminated several race conditions by analyzing and restructuring loading process.
      - Oversaw migration of complicated server to new data center.
  athenahealth:
    subsystems:
      - Divided over 2 million lines of Perl code into 30+ business domains.
      - Redesigned intranet site based on feedback gathered from users.
    qaqueue:
      - Led a team of developers working on automated testing and release deployment.
      - Refactored disparate ad-hoc interactions with Perforce into a single consistent interface.
      - Ported Epocrates' databases onto athenahealth's database migration logic.
    regressions:
      - Built an asset management system used by most automated testing infrastructure.
      - Built a job management system scaling regression testing from 8 to over 40 databases.
    clinicals:
      - Automated development process for creating interfaces between practices and several labs.
      - Created infrastructure allowing interfaces role to scale during a period of exponential growth.
      - Triaged bugs reported by clients during the alpha phase of Clinicals.
